---
- client_id: EB:D2:46:C7:7A:B8:DC:48:9D:AB:1D:31:2A:08:41:48:D7:5F:12:55:keyid:C4:76:D0:AA:CD:93:79:35:0F:EB:A7:64:60:90:A4:6B:B4:38:4D:33
  client_name: broker
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://broker.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: edd4bf74e9850f8a55b82f410db228e1a46d884ea533d721e18405e2769edcb9
- client_id: 62:4A:F7:CE:76:C8:BE:05:D6:13:41:18:57:16:59:AC:E1:70:BB:D3:keyid:13:08:41:39:35:83:7E:65:56:1A:1B:C6:E5:B8:86:F3:B4:7C:0D:D2
  client_name: connectorA
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://connectorA.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: 6facc7fbc15ad4b89d465c676cbd274ad923520cc28964e54238b9f4ec5a2b23
- client_id: F6:82:CB:05:CF:B6:55:BE:81:5C:20:C4:2E:35:3C:28:E9:08:A4:88:keyid:13:08:41:39:35:83:7E:65:56:1A:1B:C6:E5:B8:86:F3:B4:7C:0D:D2
  client_name: connectorB
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://connectorB.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: 7351921564c505c75012bacacf4d1f458f68ebd9a4646ed9c8b8621c73d56bfc
